# Generated by Django 5.2.13 on 2026-04-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('LOGIN_FAILED', '登录失败'), ('LOGIN_LOCK_TRIGGERED', '触发封禁'), ('LOGIN_LOCK_BLOCKED', '封禁中拦截'), ('LOGIN_SUCCESS', '登录成功'), ('LOGIN_FAILURES_RESET', '失败计数重置')], db_index=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_security_logs',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['username', '-created_at'], name='auth_securi_usernam_c44b30_idx'), models.Index(fields=['client_ip', '-created_at'], name='auth_securi_client__d5fb6c_idx')],
            },
        ),
    ]
